import { Product } from "./types";

export const products : Product[] = [
    {
     id: 1 ,
     title: "Eyes Liner",
     imgage: ["/foryou12.jpeg"],
    detail : "Adhesive-Liquid-Eyliner", 
    price: 54, 
    catogry : "eyes",
    description:"Smooth Eyeliner. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "#964b00"],
    quantity: 1,
    },
    {
        id: 2 ,
     title: "Red Matte Lipstick ",
     imgage: ["/foryou11.jpeg"],
    detail : "huda-beauty-red", 
    price: 500, 
    catogry : "lips",
    description:"Huda beauty red mate lipstick Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
        id: 3 ,
     title: "Eye shadow palet ",
     imgage: ["/foryou3.jpg"],
    detail : "eyeshade-palet", 
    price: 500, 
    catogry : "eyes",
    description:"Eye shadow palet by huda beauty with different shades Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
        id: 4 ,
     title: "Pink beauty blender",
     imgage: ["/foryou4.jpeg"],
    detail : "beauty-blender", 
    price: 500, 
    catogry : "accessories",
    description:"Original Beauty blender Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
        id: 5 ,
     title: "Eyes Liner",
     imgage: ["/foryou5.jpeg"],
    detail : "skin556", 
    price: 500, 
    catogry : "skincare",
    description:"Eyeliner  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
        id: 6 ,
     title: "Mroccanoil Color conditinar",
     imgage: ["/foryou6.jpg"],
    detail : "color-conditinor", 
    price: 500, 
    catogry : "hair",
    description:"Mroccanoil Color conditinar Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
        id: 7 ,
     title: "Maybelline Fit Me Foundation ",
     imgage: ["/foryou7.jpg"],
    detail : "fit-me-foundation", 
    price: 4000, 
    catogry : "face",
    description:"Maybelline Fit Me Foundation Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
     id: 8 ,
     title: "Blush on by NRAS",
     imgage: ["/foryou8.jpg"],
    detail : "blush-on", 
    price: 500, 
    catogry : "face",
    description:"Thick lipstick type blush on for your lips and cheeks too Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
        id: 9 ,
     title: "Pink shini lip balm",
     imgage: ["/foryou9.jpg"],
    detail : "pink-shine-lip-balm", 
    price: 500, 
    catogry : "lips",
    description:"Lip balm by LANCOME juicy tubes original Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
        id: 10 ,
     title: "Fake Nails",
     imgage: ["/foryou10.jpg"],
    detail : "Fake-nais", 
    price: 500, 
    catogry : "nails",
    description:"Fake nails with longlasting glue Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#ffffff" , "#000000" , "e60000"],
    quantity: 1,
    },
    {
    id: 11 ,
     title: "Mascara",
     imgage: ["/mascara.jpg"],
    detail : "mascara-honest", 
    price: 600, 
    catogry : "eyes",
    description:"Mascara by Honest .Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
    //color : ["#023e8a" , "#212529" , "#9ef01a"],
    quantity: 1,
    },
    {
        id: 12 ,
        title: "Palet of Gliter shades",
        imgage: ["/gletarshad.jpg"],
        detail : "gliter-palet", 
        price: 1000, 
        catogry : "eyes",
        description:"Palet of best shades of  Gliter.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
        //color : ["#023e8a" , "#212529" , "#9ef01a"],
        quantity: 1,
    },
    {
        id: 13 ,
        title: "Palet of nude shade of eye shadow",
        imgage: ["/eyeshadownude.webp"],
        detail : "eye-shadow-of-nude-shade", 
        price: 1000, 
        catogry : "eyes",
        description:"Palet of beautiful nude shades shadow .Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       // color : ["#023e8a" , "#212529" , "#9ef01a"],
        quantity: 1,
    },
    {
        id: 14 ,
        title: "3 pages book of eye shadow ",
        imgage: ["/packof3shad.webp"],
        detail : "makeup-shadow-book", 
        price: 1500, 
        catogry : "eyes",
        description:"3 pages beautiful book of eye shadow with multiple colors .Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
        //color : ["#023e8a" , "#212529" , "#9ef01a"],
        quantity: 1,
    },
    {
        id: 15 ,
        title: "5 Gliter shades",
        imgage: ["/pakeofgletar.jpg"],
        detail : "gliter-3", 
        price: 900, 
        catogry : "eyes",
        description:"5 mini Gliter shades .Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
        //color : ["#023e8a" , "#212529" , "#9ef01a"],
        quantity: 1,
    },
    {
        id: 15 ,
        title: "Concelar by honest",
        imgage: ["/concelar.jpg"],
        detail : "concelar-for-eye", 
        price: 500, 
        catogry : "eyes",
        description:"Concelar Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
        //color : ["#023e8a" , "#212529" , "#9ef01a"],
        quantity: 1,
    },
    {
        id: 16 ,
        title: "Kajal and white pencil",
        imgage: ["/kajalandwhite.png"],
        detail : "kajal-white", 
        price: 500, 
        catogry : "eyes",
        description:"Kajal and white pencile both at 1 package Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
        //color : ["#023e8a" , "#212529" , "#9ef01a"],
        quantity: 1,
    },
    {
        id: 17 ,
        title: "Under eye masks for dark circles",
        imgage: ["/undereye.jpg"],
        detail : "under-eye-mask", 
        price: 1500, 
        catogry : "eyes",
        description:"Fortive green tea eye gal pads, Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       // color : ["#023e8a" , "#212529" , "#9ef01a"],
        quantity: 1,
    },
    {
        id: 18 ,
        title: "Powder Foundation",
        imgage: ["/powder.webp"],
       detail : "Powder-Foundation", 
       price: 1000, 
       catogry : "face",
       description:"Shebeauty - from where the beauty begins Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       //color : ["#ffffff" , "#000000" , "#964b00"],
       quantity: 1,
       },
       {
        id: 19 ,
        title: "Maybelline fit me foundation matte",
        imgage: ["/5mlfoun.webp"],
       detail : "maybline-fitme-5ml", 
       price: 300, 
       catogry : "face",
       description:"Poreless 5ml sachet 120 classic begins Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       //color : ["#ffffff" , "#000000" , "#964b00"],
       quantity: 1,
       },
       {
        id: 20 ,
        title: "Iconic London Liquid Highliter",
        imgage: ["/liquidshine.jpg"],
       detail : "iconic-London-Liquid", 
       price: 1000, 
       catogry : "face",
       description:"Civaki professionals iconic London Liquid Highliter for face shine-30ml Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       //color : ["#ffffff" , "#000000" , "#964b00"],
       quantity: 1,
       },
       {
        id: 21 ,
        title: "Moisturizing Liquid Blush",
        imgage: ["/blushliquid2.jpeg"],
       detail : "iconic-London-Liquid", 
       price: 800, 
       catogry : "face",
       description:"Dolce vita liquid moisturizing blush Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       //color : ["#ffffff" , "#000000" , "#964b00"],
       quantity: 1,
       },
       {
        id: 22 ,
        title: "Moisturizing Baby skin Primer",
        imgage: ["/babyskin.jpg"],
       detail : "iconic-London-Liquid", 
       price: 1000, 
       catogry : "face",
       description:"Maybelline baby skin instant pore eraser primew makeup, Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 23 ,
        title: "Sun Sculpt liquid contour",
        imgage: ["/contour.jpg"],
       detail : "liquid-contour", 
       price: 1500, 
       catogry : "face",
       description:"Sun Sculpt liquid contour Golden sun sheglam beauty Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 24 ,
        title: "Lip Liner Matte lips",
        imgage: ["/lipliner.jpg"],
       detail : "lip-liner", 
       price: 500, 
       catogry : "lips",
       description:"Set-12 assorted color high pigment natural lip makeup soft pencils. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 25 ,
        title: "Lip scrub ",
        imgage: ["/lipscrub.jpeg"],
       detail : "lip-scrub", 
       price: 1000, 
       catogry : "lips",
       description:"Pink Graprfruit Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 25 ,
        title: "Lip mask",
        imgage: ["/lipmask.jpg"],
       detail : "lip-mask", 
       price: 500, 
       catogry : "lips",
       description:"Moisturizing lips mask set collagen lips sleep mask reduces lips line and give natural moisturizing Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 26 ,
        title: "Lip Gel",
        imgage: ["/lipgel.jpeg"],
       detail : "lip-gel", 
       price: 900, 
       catogry : "lips",
       description:"Moisturizing lips gel set collagen lips sleep gel and also for day time reduces lips line and give natural moisturizing Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 27 ,
        title: "Lip Balm",
        imgage: ["/lipbalm.jpg"],
       detail : "lip-balm", 
       price: 300, 
       catogry : "lips",
       description:"Moisturizing lips balm set collagen lips sleep gel and also for day time reduces lips line and give natural moisturizing Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 27 ,
        title: "Lipstick",
        imgage: ["/lipstick.webp"],
       detail : "lip-stick-nude", 
       price: 600, 
       catogry : "lips",
       description:"Nude look perfect matte lipstick New Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 28 ,
        title: "Nail paint",
        imgage: ["/nailpaint.webp"],
       detail : "nail-paint", 
       price: 300, 
       catogry : "nails",
       description:"ST london - colorist nail pain ST001 Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 29 ,
        title: "Pack of 5 Nail paint",
        imgage: ["/nailpack.jpeg"],
       detail : "nail-paint-pack", 
       price: 3000, 
       catogry : "nails",
       description:"Buy juice nail paint- pickle green, sky blue, french purple, coral sunset, amaranth pink  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 30,
        title: "Nail polish remover",
        imgage: ["/nailpolisjremover.jpg"],
       detail : "nail-paint-remover", 
       price: 100, 
       catogry : "nails",
       description:"Medora nail polish remover Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 31,
        title: "5 pcs of pink makeup brushes",
        imgage: ["/brushes.jpg"],
       detail : "makeup-brush", 
       price: 300, 
       catogry : "accessories",
       description:"Frosted cosmetic 6155 makeup kit with 5 pcs pink Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 32,
        title: "Generic heart velvet powder puff",
        imgage: ["/makeuppuff.jpeg"],
       detail : "makeup-brush", 
       price: 300, 
       catogry : "accessories",
       description:"Mini face makeup sponge costemics washable lightweight makeup Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 33,
        title: "Makeup brushes",
        imgage: ["/lightbrush.jpeg"],
       detail : "makeup-brush-minis", 
       price: 400, 
       catogry : "accessories",
       description:"Brushes for lip , eyes and nose lightweight makeup brushes Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 34,
        title: "Sunsilk",
        imgage: ["/shampoo.jpeg"],
       detail : "shampoo-sunsilk", 
       price: 400, 
       catogry : "hair",
       description:"Sunsilk pink shine Shampoo Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 35,
        title: "Loreal paris conditioner",
        imgage: ["/conditinor.webp"],
       detail : "conditinor-loreal", 
       price: 500, 
       catogry : "hair",
       description:"Loreal paris advance haircare smooth intense polishing conditioner Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 36,
        title: "Argan hair oil",
        imgage: ["/hairoil.jpeg"],
       detail : "hair-oil", 
       price: 500, 
       catogry : "hair",
       description:" Argon hair oil treatment 100ml Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 37,
        title: "Hair growth serum",
        imgage: ["/hairserum.jpg"],
       detail : "hair-serum", 
       price: 500, 
       catogry : "hair",
       description:" Dr. Daddy natural hair growth serum  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 38,
        title: "BHA 2% peeling",
        imgage: ["/serum.jpeg"],
       detail : "serum-aha", 
       price: 500, 
       catogry : "skincare",
       description:"The ordinary aha 30% + bha 2% peeling solution Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 39,
        title: "Face wash",
        imgage: ["/foryoueleven.jpg"],
       detail : "glow-with-anusha", 
       price: 500, 
       catogry : "skincare",
       description:"By glowwith anusha facewash with best ingridiants Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },
       {
        id: 40,
        title: "Face Mask",
        imgage: ["/facemask.jpeg"],
       detail : "face-mask", 
       price: 500, 
       catogry : "skincare",
       description:"The creme shop vitamin C face mask, cute animal face mask korean Lorem ipsum dolor sit, amet consectetur adipisicing elit. Libero ex dicta maiores? Quae odit ipsum dolorum incidunt optio!",
       quantity: 1,
       },


]